### ISSUE TITLE
DRZ80 not working

### ISSUE THREAD

**Issue by wn2000** [libretro/mame2003-plus-libretro#1701]
_Originally posted by @wn2000 in https://github.com/libretro/mame2003-plus-libretro/pull/766#discussion_r1545536526_

**Comment by mahoneyt944** [comment]
Are you testing this with the current core? This core now has core options to force enable these modes.

**Comment by mahoneyt944** [comment]
If you force enable one of these modes, check the info log that it replaced the CPU

https://github.com/libretro/mame2003-plus-libretro/blob/ee777f235b99d652890dedbc94337094968869d4/src/mame2003/mame2003.c#L1693

**Comment by wn2000** [comment]
To be clear there are two issues:

1. The bug on these lines prevents the CPU replacement (as it's comparing a pointer address against an enum):

https://github.com/libretro/mame2003-plus-libretro/blob/ee777f235b99d652890dedbc94337094968869d4/src/mame2003/mame2003.c#L1690

https://github.com/libretro/mame2003-plus-libretro/blob/ee777f235b99d652890dedbc94337094968869d4/src/mame2003/mame2003.c#L1704

2. After fixing this bug (so the log correctly shows "Replaced Z80"), some sound effects are missing (tested with `sdfight` before and after the fix).
So there's some issue with the original PR that added the DrZ80 support.

**Comment by mahoneyt944** [comment]
It's possible the replacement CPU isn't fully compatible as the original. I'd assume this would be a case by case type of thing. Are the replacement cpus working at all after your fix?... to confirm the replaced cpu is operational at least even if buggy?

The core option allows you to replace a main z80 CPU, z80 sound CPU, or both....so there maybe specific combo that works better for some games than others.

**Comment by wn2000** [comment]
Yeah so it seems DrZ80 doesn't work at all. Tried 88 games, with Cyclone+DrZ80 it freezes at the ROM OK screen; with Cyclone only it works fine.
But Cyclone also has issues. AvP would black screen if Cyclone is enabled.

So, maybe not worth it after all.

**Comment by arcadez2003** [comment]
Yeah as i commented at the time the cyclone cpu cores are buggy for a fair few games but boost up the performance
of many others, i suppose back in the day a list would have been made as to which games should be played using it
and which should not.

But no one can be bothered with such undertakings nowadays :)

**Comment by wn2000** [comment]
Looks like cyclone received some updates recently:

https://github.com/notaz/cyclone68000/commits/master/

**Comment by grant2258** [comment]
@wn2000 apologies I checked the binary as i recently ported this to mame2003-xtreme. It is indeed going to black screen looking at the code the interrupts dont play nice. Ill see if i can hack 88 games at the weekend for it to boot for you. It doesn't look like is respecting the LINE_HOLD vector being sent but games like rygar are working fine. That is flipping through the interrupts  fine. Looks like the mame this came from handled ignoring interrupts differently to this core.

**Comment by mahoneyt944** [comment]
> @wn2000 apologies I checked the binary as i recently ported this to mame2003-xtreme. It is indeed going to black screen looking at the code the interrupts dont play nice. Ill see if i can hack 88 games at the weekend for it to boot for you. It doesn't look like is respecting the LINE_HOLD vector being sent but games like rygar are working fine. That is flipping through the interrupts fine. Looks like the mame this came from handled ignoring interrupts differently to this core.

Do we need to use the drz80 flag to return or something?

**Comment by grant2258** [comment]
> Do we need to use the drz80 flag to return or something?

Not sure what you mean the issue is the interrupts are handled differently on  mame2000. We done get the IGNORE calls in the interrupt states processing like 2000 does. So the 68k is basically going to need fixed as well. 

or core
https://github.com/libretro/mame2003-plus-libretro/blob/ae63a9992db027139f934ce19a0ecdfc7d6edfc1/src/cpuintrf.c#L336-L337

2000
https://github.com/libretro/mame2000-libretro/blob/2ec60f6e1078cf9ba173e80432cc28fd4eea200f/src/cpuintrf.c#L382-L383

I think its sticking on with the interrupt hold line after its set and not clearing could be wrong though. Ill need to see what really happening our end to see where its going wrong with the interrupts in the drz80. I if I have some free time to dig in at the weekend ill look into it in more detail.

**Comment by grant2258** [comment]
@wn2000 the fix was thankfully easy was just the cycles. fix is here 88 games now boot. It was missing a cycle now and then havent looked at the 68k at all but the fix is here if you want to test. https://github.com/libretro/mame2003-plus-libretro/pull/1814/files

**Comment by mahoneyt944** [comment]
Nice, merged

**Comment by grant2258** [comment]
@KMFDManic there is an issue with the frontend_list not disabling games when its not in the front end list. Ill put a fix in on your port as well as some logging when a game has a z80 or 68k and its not on the list so you know if you want to add it or not. I cant speak for the lists accuracy though .

**Comment by mahoneyt944** [comment]
Can we close this now?

**Comment by grant2258** [comment]
Yea the z80 issue is fixed the frontend_list is int correctly processed though but thats a separate issue. Im going apply the fixes on @KMFDManic port. I know he is in a position to test it and people can use it. Will let you know when its done and you can decide any changes for this core.

**Comment by grant2258** [comment]
@mahoneyt944 thats it finished up on KMFDManic there is one pull request that need pulled so you can decide what you want to do this end. I would recommend you enable it for the pi2 and 3 after its tested of course.

**Comment by mahoneyt944** [comment]
@grant2258 this should sync up the latest work
https://github.com/libretro/mame2003-plus-libretro/commit/4adf11f0eb893288c1f47df805dc88bce409303d

**Comment by mahoneyt944** [comment]
I think there's still an issue to iron out, we don't clearly distinguish between DrZ80 and DrZ80(snd) replacements. If we select core option 4 `DrZ80(snd)`, it should only replace a z80 sound CPU, but not any other z80 cpus if present and vice versa.

**Comment by grant2258** [comment]
Well the z80 has issues its like that for a reason at the moment. Its going to be disabled on the other port for now as well until the interrupts are fixed properly. If just a matter of adding another if condition nothing major.

Not all sound cpus are flagged anyway but probably should be added properly in cases it gets fixed.

**Comment by mahoneyt944** [comment]
Maybe like this? And we can update the flag as we come across them

- Z80, use_drz80, without a CPU_AUDIO_CPU flag
- Z80, use_drz80_snd, with a CPU_AUDIO_CPU flag

```
#if (HAS_DRZ80)
  /* Replace Z80 by DRZ80 */
  if (use_drz80)
  {
    for (i=0;i<MAX_CPU;i++)
    {
      unsigned int *type=(unsigned int *)&(Machine->drv->cpu[i].cpu_type);
     if (*type==CPU_Z80 && !(Machine->drv->cpu[i].cpu_flags&CPU_AUDIO_CPU))
      {
        *type=CPU_DRZ80;
        log_cb(RETRO_LOG_INFO, LOGPRE "Replaced Z80\n");
      }
    }
  }

  /* Replace Z80 with DRZ80 only for sound CPUs */
  if (use_drz80_snd)
  {
    for (i=0;i<MAX_CPU;i++)
    {
     unsigned int *type=(unsigned int *)&(Machine->drv->cpu[i].cpu_type);
     if (*type==CPU_Z80 && Machine->drv->cpu[i].cpu_flags&CPU_AUDIO_CPU)
      {
        *type=CPU_DRZ80;
        log_cb(RETRO_LOG_INFO, LOGPRE "Replaced Z80 sound\n");
      }
    }
  }
#endif
```

**Comment by mahoneyt944** [comment]
How much benefit does this even have, has anyone actually done back to back speed tests to see how much performance this even makes?

**Comment by KMFDManic** [comment]
@mahoneyt944 @grant2258 as an example, just testing cyclone before and after, it was definitely a noticeable difference. If you have anything in place in Xtreme that would allow me to do before and after results in a video, let me know for cyclone or the Z80, and I can showcase either or.  Cyclone helped a lot on fbneo for mushihimesama and deathsmiles.  On Plus/Xtreme, it helped with Killer Instinct.  Just need more test subjects and I can yield us some differentials between before and after.

**Comment by grant2258** [comment]
It makes a difference in lower end can test it myself just limited a small memory card. I think ill install raspberry pios takes less space than the retropie and thats really outdated as well no new os image.

**Comment by mahoneyt944** [comment]
I just split them for now, I guess it comes down to what's the intention of "2=DrZ80".....to replace all z80's found or only non sound z80's? I take that as replace all of them.

**Comment by grant2258** [comment]
Its a flag only some drivers set its doesnt really matter per say. If its flagged in the driver its will work as intended. Its fixed and separated on the other port  as well. The core options also need conditioned.

**Comment by mahoneyt944** [comment]
Realistically how many platforms will set one without the other? Seems to me if it needs to use either of these replacements cpus then both should be available to try. It's also probably a bad idea to configure a core option that way because if a core is recompiled with different flags set in the makefile it opens the the possibility for RA to initialize the option with a value that's no longer available.

**Comment by grant2258** [comment]
@mahoneyt944 I not too bothered what you do here. Its not and issue if its unknown option its still processed it just going too do nothing until you set it properly in the core options to what you want. It make no sense to add options for things not enabled.  Feel free to do anything on your end no one is going to bat an eye lid its all personal preference.

**Comment by grant2258** [comment]
The z80 has been fixed on the @KMFDManic  port now had the time to debug it. Its interesting the mame2000 added a new cpu type to work round the problem. I checked how they it after I debugged it our end.

**Comment by mahoneyt944** [comment]
Resync with xtreme for cyclone and drz80 changes https://github.com/libretro/mame2003-plus-libretro/commit/5f98dc3cf18cee1e2e9d0264d5851f612642d6e7
