### ISSUE TITLE
invaders samples notification & artwork

### ISSUE THREAD

**Issue by 2xtime** [libretro/mame2003-plus-libretro#560]
When playing Space Invaders (invaders.zip), Retroarch says there is missing samples but I have the samples in the samples directory and they work. I got them from Twisty's site and in the zip file there are 19 samples (Original set and enhanced set) but mame2003plus datfile only has 1.wav to 9.wav ?

Also, is the background artwork supposed to look like that ? It's in widescreen ?

**Comment by arcadez** [comment]
Your samples for Space Invaders are wrong, you'd need your invaders.zip to match up with MAME78

0.111u1: Tomasz Slanina added clone Darth Vader (bootleg). Added more samples (11-18.wav) to the Invaders set. Robert added the game toggle switch to Jatre Specter (move right for game B; otherwise it's game A).

**Comment by markwkidd** [comment]
@2xtime if you produce a verbose log, mame2003-plus will tell you the exact filenames of the samples it is missing

**Comment by 2xtime** [comment]
@markwkidd The log file just says -

[libretro WARN] [MAME 2003+] Warning: audio sample(s) not found.
[INFO] Environ SET_MESSAGE: Warning: audio sample(s) not found.
[libretro INFO] [MAME 2003+] 

I got the samples from Twisty's and it contains all that @arcadez listed above. Do you know where to get the "correct" samples ? I think it would be a good idea to put a correct set in the metadata folder as they are quite integral ! And do you know if the artwork for invaders is supposed to be displayed in widescreen ? It doesn't look like this on windows Mame (Mr. Do's).

Also, the datfile says i'm not missing any samples.

**Comment by markwkidd** [comment]
A few lines above those in the log ought to have specific filenames. There
may be a little bit of unrelated log in the middle.




On Dec 28, 2018 11:42 AM, "2xtime" <notifications@github.com> wrote:

@markwkidd <https://github.com/markwkidd> The log file just says -

[libretro WARN] [MAME 2003+] Warning: audio sample(s) not found.
[INFO] Environ SET_MESSAGE: Warning: audio sample(s) not found.
[libretro INFO] [MAME 2003+]

I got the samples from Twisty's and it contains all that @arcadez
<https://github.com/arcadez> listed above. Do you know where to get the
"correct" samples ? I think it would be a good idea to put a correct set in
the metadata folder as they are quite integral ! And do you know if the
artwork for invaders is supposed to be displayed in widescreen ? It doesn't
look like this on windows Mame (Mr. Do's).

Also, the datfile says i'm not missing any samples.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/libretro/mame2003-plus-libretro/issues/560#issuecomment-450389064>,
or mute the thread

**Comment by Wilstorm** [comment]
Just to add to this I am seeing the same issue also on commit b366898 where RGUI is displaying that message in the lower left corner of games with samples. I tested berzerk, invaders & dkong. Also when testing I found Berzerk isn't working. When I launch the game it flashes some color real quick and goes to a blank/black screen and that's it. Here's the verbose log if it helps and mame2003 does launch berzerk.

```
Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so --config /opt/retropie/configs/arcade/retroarch.cfg "/home/pi/RetroPie/roms/arcade/berzerk.zip" --verbose --appendconfig /dev/shm/retroarch.cfg'|'"/home/pi/RetroPie/roms/arcade/berzerk.zip.cfg"
[INFO] RetroArch 1.7.5 (Git c9c6c5a)
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/arcade/berzerk.srm".
[INFO] Redirecting savestate to "/home/pi/RetroPie/roms/arcade/berzerk.state".
[INFO] === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Nov 19 2018
[INFO] Version: 1.7.5
[INFO] Git: c9c6c5a
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so"
[INFO] [overrides] no core-specific overrides found at /home/pi/.config/retroarch/config/MAME 2003-Plus/MAME 2003-Plus.cfg.
[INFO] [overrides] no content-dir-specific overrides found at /home/pi/.config/retroarch/config/MAME 2003-Plus/arcade.cfg.
[INFO] [overrides] no game-specific overrides found at /home/pi/.config/retroarch/config/MAME 2003-Plus/berzerk.cfg.
[INFO] Shaders: preset directory: /home/pi/.config/retroarch/shaders/presets
[INFO] Shaders: no game-specific preset found at /home/pi/.config/retroarch/shaders/presets/MAME 2003-Plus/berzerk.cgp.
[INFO] Shaders: no game-specific preset found at /home/pi/.config/retroarch/shaders/presets/MAME 2003-Plus/berzerk.glslp.
[INFO] Shaders: no content-dir-specific preset found at /home/pi/.config/retroarch/shaders/presets/MAME 2003-Plus/arcade.cgp.
[INFO] Shaders: no content-dir-specific preset found at /home/pi/.config/retroarch/shaders/presets/MAME 2003-Plus/arcade.glslp.
[INFO] Shaders: no core-specific preset found at /home/pi/.config/retroarch/shaders/presets/MAME 2003-Plus/MAME 2003-Plus.cgp.
[INFO] Shaders: no core-specific preset found at /home/pi/.config/retroarch/shaders/presets/MAME 2003-Plus/MAME 2003-Plus.glslp.
[INFO] Remaps: remap directory: /opt/retropie/configs/arcade/
[INFO] Remaps: no game-specific remap found at /opt/retropie/configs/arcade/MAME 2003-Plus/berzerk.rmp.
[INFO] Remaps: no content-dir-specific remap found at /opt/retropie/configs/arcade/MAME 2003-Plus/arcade.rmp.
[INFO] Remaps: core-specific remap found at /opt/retropie/configs/arcade/MAME 2003-Plus/MAME 2003-Plus.rmp.
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/arcade/berzerk.srm".
[INFO] Redirecting savestate to "/home/pi/RetroPie/roms/arcade/berzerk.state".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ PERFORMANCE_LEVEL: 10.
[INFO] Content loading skipped. Implementation will load it on its own.
[libretro INFO] [MAME 2003+] Content path: /home/pi/RetroPie/roms/arcade/berzerk.zip.
[libretro INFO] [MAME 2003+] Content lookup name: berzerk.
[libretro INFO] [MAME 2003+] Driver index counter: 3671. Matched game driver: berzerk.
[libretro INFO] [MAME 2003+] Content identified as using 8-way joystick controls.
[libretro INFO] [MAME 2003+] Content identified by controls.c as having joysticks on axis with respect to the cabinet.
[libretro INFO] [MAME 2003+] Content identified as supporting 2 players with 2 distinct controls.
[libretro INFO] [MAME 2003+] Content identified as supporting 1 button controls.
[libretro INFO] [MAME 2003+] Content identified by controls.c as having mirrored multiplayer control labels.
[INFO] Environ SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] [MAME 2003+] content path: /home/pi/RetroPie/roms/arcade/
[libretro INFO] [MAME 2003+]  system path: /home/pi/RetroPie/BIOS
[libretro INFO] [MAME 2003+]    save path: /home/pi/RetroPie/roms/arcade/
[INFO] Environ SET_VARIABLES.
[INFO] Environ GET_VARIABLE mame2003-plus_four_way_emulation:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_mouse_device:
[INFO] 	mouse
[INFO] Environ GET_VARIABLE mame2003-plus_crosshair_enabled:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_skip_disclaimer:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_skip_warnings:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_display_setup:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE mame2003-plus_neogeo_bios:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_stv_bios:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_use_alt_sound:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_dialsharexy:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_dual_joysticks:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_rstick_to_btns:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_vector_resolution_multiplier:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_vector_antialias:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_vector_beam_width:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_vector_translucency:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_vector_flicker:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_vector_intensity:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_dcs_speedhack:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_core_sys_subfolder:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_core_save_subfolder:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_tate_mode:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE mame2003-plus_input_interface:
[INFO] 	mame
[INFO] Environ GET_VARIABLE mame2003-plus_brightness:
[INFO] 	1.0
[INFO] Environ GET_VARIABLE mame2003-plus_gamma:
[INFO] 	1.2
[INFO] Environ GET_VARIABLE mame2003-plus_frameskip:
[INFO] 	0
[INFO] Environ GET_VARIABLE mame2003-plus_sample_rate:
[INFO] 	48000
[INFO] Environ GET_VARIABLE mame2003-plus_mame_remapping:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_display_artwork:
[INFO] 	enabled
[INFO] Environ GET_VARIABLE mame2003-plus_art_resolution:
[INFO] 	2
[INFO] Environ GET_VARIABLE mame2003-plus_nvram_bootstraps:
[INFO] 	N/A
[INFO] Environ GET_VARIABLE mame2003-plus_cheat_input ports:
[INFO] 	disabled
[INFO] Environ GET_VARIABLE mame2003-plus_machine_timing:
[INFO] 	enabled
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    Gamepad (ID: 1)
[INFO]    8-Button (ID: 257)
[INFO]    6-Button (ID: 513)
[INFO]    Classic Gamepad (ID: 769)
[INFO] Controller port: 2
[INFO]    Gamepad (ID: 1)
[INFO]    8-Button (ID: 257)
[INFO]    6-Button (ID: 513)
[INFO]    Classic Gamepad (ID: 769)
[INFO] Controller port: 3
[INFO]    UNSUPPORTED (Gamepad) (ID: 1)
[INFO]    UNSUPPORTED (8-Button) (ID: 257)
[INFO]    UNSUPPORTED (6-Button) (ID: 513)
[INFO]    UNSUPPORTED (Classic Gamepad) (ID: 769)
[INFO] Controller port: 4
[INFO]    UNSUPPORTED (Gamepad) (ID: 1)
[INFO]    UNSUPPORTED (8-Button) (ID: 257)
[INFO]    UNSUPPORTED (6-Button) (ID: 513)
[INFO]    UNSUPPORTED (Classic Gamepad) (ID: 769)
[INFO] Controller port: 5
[INFO]    UNSUPPORTED (Gamepad) (ID: 1)
[INFO]    UNSUPPORTED (8-Button) (ID: 257)
[INFO]    UNSUPPORTED (6-Button) (ID: 513)
[INFO]    UNSUPPORTED (Classic Gamepad) (ID: 769)
[INFO] Controller port: 6
[INFO]    UNSUPPORTED (Gamepad) (ID: 1)
[INFO]    UNSUPPORTED (8-Button) (ID: 257)
[INFO]    UNSUPPORTED (6-Button) (ID: 513)
[INFO]    UNSUPPORTED (Classic Gamepad) (ID: 769)
[libretro INFO] [MAME 2003+] Opening ROM file: 1c-0
[libretro INFO] [MAME 2003+] Opening ROM file: 1d-1
[libretro INFO] [MAME 2003+] Opening ROM file: 3d-2
[libretro INFO] [MAME 2003+] Opening ROM file: 5d-3
[libretro INFO] [MAME 2003+] Opening ROM file: 6d-4
[libretro INFO] [MAME 2003+] Opening ROM file: 5c-5
[libretro INFO] [MAME 2003+] Succesfully loaded ROMs.
[libretro ERROR] cpunum_get_localtime() called for invalid cpu num!
[INFO] Environ SET_ROTATION: 0
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[libretro WARN] [MAME 2003+] Warning: audio sample(s) not found.
[INFO] Environ SET_MESSAGE: Warning: audio sample(s) not found.
[libretro INFO] [MAME 2003+] 

CONTROLS: 

GAMEINFO: Berzerk (set 1)
1980 Stern

CPU:
Z80 2.500000 MHz

Sound:
Samples
Custom

Screen Resolution:
256 x 224 (H) 60.000000 Hz
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 897x672
[INFO] [Video]: Starting threaded video driver ...
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: videocore
[INFO] [GL]: Detecting screen resolution 1920x1200.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] Querying EGL extension: KHR_image => exists
[WARN] [GL]: GLES implementation does not have BGRA8888 extension.
32-bit path will require conversion.
[INFO] [GL]: Using resolution 1920x1200
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] Found #pragma parameter Screen curvature - horizontal (CURVATURE_X) 0.100000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Screen curvature - vertical (CURVATURE_Y) 0.150000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Mask brightness (MASK_BRIGHTNESS) 0.700000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Scanline weight (SCANLINE_WEIGHT) 6.000000 0.000000 15.000000 0.100000 in pass 0
[INFO] Found #pragma parameter Scanline gap brightness (SCANLINE_GAP_BRIGHTNESS) 0.120000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Bloom factor (BLOOM_FACTOR) 1.500000 0.000000 5.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Input gamma (INPUT_GAMMA) 2.400000 0.000000 5.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Output gamma (OUTPUT_GAMMA) 2.200000 0.000000 5.000000 0.010000 in pass 0
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ... 
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] [udev]: Keyboard #0 (/dev/input/event0).
[INFO] [udev]: Keyboard #1 (/dev/input/mouse0).
[ERROR] [udev] Failed to open device: /dev/input/event0 (Success).
[INFO] [udev]: Mouse #0 (/dev/input/mouse0).
[INFO] [Joypad]: Found joypad driver: "udev".
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [Video]: Found display server: null
[INFO] Found shader "/home/pi/.config/retroarch/shaders/2xsal-level2-crt.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/2xsal.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/2xScaleHQ.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/barrel-distortion.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/barrel-distortion_lanczos4.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/barrel-distortion_phosphor.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/barrel-distortion_snes.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/Brighter-with_Contrast.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/bsnes_gamma_ramp.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/crt-pi-curvature-vertical.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/crt-pi-curvature.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/crt-pi-vertical.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/crt-pi.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/gameboy-screen-grid.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/gameboy.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/gameboy2.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/gba-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x&lcd3x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x2.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x_lcd3x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2x_phosphor.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2xwaterpaint.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq2xwaterpaintscanline.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq4x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/hq4x_lcd3x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/nds-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/nds.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/nedi.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/palm-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/phosphor.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/psp-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/sharp-bilinear-2x-prescale.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/sharp-bilinear-scanlines.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/sharp-bilinear-simple.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes2.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_hq2x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_hq2xwaterpaint.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_hq2xwaterpainthicontrast.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_hq2xwaterpaintscanline.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_lcd3x.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_phosphor.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_scanline.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/snes_waterpaint.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/stock.glsl"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/super-2xsai.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/super-eagle.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/vba-color.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/xbr-lv1-noblend.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_crt_curve.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_crt_curve_vertical.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_crt_standard.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_crt_standard_vertical.glslp"
[INFO] Found shader "/home/pi/.config/retroarch/shaders/zfast_lcd_standard.glslp"
[INFO] ALSA: Using signed 16-bit format.
[INFO] ALSA: Period size: 384 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] Found #pragma parameter Screen curvature - horizontal (CURVATURE_X) 0.100000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Screen curvature - vertical (CURVATURE_Y) 0.150000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Mask brightness (MASK_BRIGHTNESS) 0.700000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Scanline weight (SCANLINE_WEIGHT) 6.000000 0.000000 15.000000 0.100000 in pass 0
[INFO] Found #pragma parameter Scanline gap brightness (SCANLINE_GAP_BRIGHTNESS) 0.120000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Bloom factor (BLOOM_FACTOR) 1.500000 0.000000 5.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Input gamma (INPUT_GAMMA) 2.400000 0.000000 5.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Output gamma (OUTPUT_GAMMA) 2.200000 0.000000 5.000000 0.010000 in pass 0
[INFO] [LED]: LED driver = 'null' 0x2b9150
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] Connecting to port 769: Classic Gamepad (ID: 1).
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] Connecting to port 769: Classic Gamepad (ID: 2).
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] Connecting to port 769: UNSUPPORTED (Classic Gamepad) (ID: 3).
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] Connecting to port 769: UNSUPPORTED (Classic Gamepad) (ID: 4).
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] Connecting to port 769: UNSUPPORTED (Classic Gamepad) (ID: 5).
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 1, Button "Select" => "Coin"
[INFO] 	RetroPad, User 1, Button "Start" => "Start"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "Button 1"
[INFO] 	RetroPad, User 2, Button "Select" => "Coin"
[INFO] 	RetroPad, User 2, Button "Start" => "Start"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right"
[INFO] Found #pragma parameter Screen curvature - horizontal (CURVATURE_X) 0.100000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Screen curvature - vertical (CURVATURE_Y) 0.150000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Mask brightness (MASK_BRIGHTNESS) 0.700000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Scanline weight (SCANLINE_WEIGHT) 6.000000 0.000000 15.000000 0.100000 in pass 0
[INFO] Found #pragma parameter Scanline gap brightness (SCANLINE_GAP_BRIGHTNESS) 0.120000 0.000000 1.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Bloom factor (BLOOM_FACTOR) 1.500000 0.000000 5.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Input gamma (INPUT_GAMMA) 2.400000 0.000000 5.000000 0.010000 in pass 0
[INFO] Found #pragma parameter Output gamma (OUTPUT_GAMMA) 2.200000 0.000000 5.000000 0.010000 in pass 0
[INFO] Loading history file: [/opt/retropie/configs/arcade/content_history.lpl].
[INFO] Loading history file: [/opt/retropie/configs/arcade/content_favorites.lpl].
[INFO] Loading history file: [/opt/retropie/configs/arcade/content_music_history.lpl].
[INFO] Loading history file: [/opt/retropie/configs/arcade/content_video_history.lpl].
[INFO] Loading history file: [/opt/retropie/configs/arcade/content_image_history.lpl].
[libretro INFO] [MAME 2003+] options.nvram_bootstrap: 0 
[libretro INFO] [MAME 2003+] Delegating population of initial NVRAM to emulated system.
[libretro INFO] [MAME 2003+] Preparing emulated CPUs for execution.
[libretro INFO] [MAME 2003+] berzerk hiscore memory map found in hiscore.dat!
[INFO] Environ SET_GEOMETRY.
[libretro INFO] [MAME 2003+] loading berzerk.hi hiscore memory file...
```

**Comment by grant2258** [comment]
ill test this problem with (berzerk) not samples it was fixed 10 days ago though ill compile the latest and check it again the samples message is something else.

**Comment by grant2258** [comment]
hopefully someone else can confirm the black screen for berzerk im not getting that on the pi or windows. The false positive for the samples does need fixed though I can confirm that.

**Comment by Wilstorm** [comment]
Was there a ROM update with the fix by chance?

**Comment by grant2258** [comment]
nothing in the logs that I can see the only difference is im not using and shaders. 

you could try deleting the nvram file and control file. Just to rule that out as well as temporarily disabling the shader to see if any of that helps beyond that i have no idea why its not working for you.

/RetroPie/roms/arcade/mame2003-plus/nvram/berzerk.nv
/RetroPie/roms/arcade/mame2003-plus/cfg/berzerk.cfg

**Comment by Wilstorm** [comment]
Yeah that's the first thing I tried, deleting the cfg and nvram files but still no luck. I also just tried removing the overlay and shaders. That was a no go too. 

When I launch I press space bar and bring up the runcommand window, change to mame2003 and it launches perfect so I have no idea why Plus is black screening. I get a quick splash of color like a post test on startup and then black. TAB, RGUI and all pull up fine though.

I'll take some more time tonight and see if I can find anything wrong but for now I can set it to use mame2003 since I use the Arcade folder it's pretty simple to jump back and forth between cores.

**Comment by grant2258** [comment]
well the only other thing I can think of for you to do is just use the latest mame2003 from the libretro buildbot. It does save you compiling and will run fine on the pie. Its just not optimized as well as it could be building it yourself. Just do the following

```
cd ~
wget https://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/mame2003_plus_libretro.so.zip
unzip mame2003_plus_libretro.so.zip
sudo cp mame2003_plus_libretro.so /opt/retropie/libretrocores/lr-mame2003-plus/mame2003_plus_libretro.so
rm mame2003_plus_libretro.so
rm mame2003_plus_libretro.so.zip
```

then run mame2003-plus as usual youll be on the latest version this way

**Comment by grant2258** [comment]
well ive put a pull request in to fix the samples missing reports so we can close this particular issue ( i thought this would have been fixed for now so just fixed it myself). 

Would you mind opening a new issue for the problems you having with berzerk @Wilstorm so it doesnt get lost in a closed issue.

**Comment by grant2258** [comment]
Well dont finding that issue @Wilstorm  it was a strange one indeed. Hopefully thats you back to normal.

**Comment by Wilstorm** [comment]
@grant2258 - I am saw this error when running Mortal Kombat (mk) yesterday. ```Warning: audio sample(s) not found.``` in the lower left corner in yellow text. I am on commit f253265. I know it's not current but I think the fix was implemented prior to this commit.

**Comment by grant2258** [comment]
probably the ost stereo/mono thing ie it if you only have the 1 samples it will just use the mono. 

if you have the 1 and 2s you have the complete stereo samples. Check your zip and see if you have the stereo or mono samples.

**Comment by Wilstorm** [comment]
That's the odd thing is I don't have the custom OST for mk in the samples directory.

**Comment by grant2258** [comment]
i just tested mk is fine here i have the stereo samples though. Final fight does report missing samples but that is right because i only have the mono samples

**Comment by Wilstorm** [comment]
Ah, so it's a setting and if it's enabled then they need to be present? I didn't know it was a setting. If it's enabled by default then that would explain it as I don't have any custom OST's loaded yet since I just rebuilt this past week. Is that under options?

**Comment by grant2258** [comment]
yes its under options use cd soundtrack if you turn it off you get no warnings

**Comment by Wilstorm** [comment]
Ah, ok, thanks for clarifying that. That makes sense what's happening. So if it's disabled and the custom OST's are present will they not load. Basically they need to be present and enabled to work properly?

**Comment by grant2258** [comment]
yea its so you can go back to the games original music if you choose to without deleting the samples

**Comment by Wilstorm** [comment]
Ok, thanks for clarifying, that's a clever feature, nicely done sir!
